### ISSUE TITLE
It doesn´t stay activated

### ISSUE THREAD

**Issue by itsdomme** [oakkitten/anki-delay-siblings#3]
Unfortunately the addon only saves one pile, that it should be activated. While learning other piles, it always has to be activated manually and when you rejoin after every adjustments in the browser it´s deactivated. 

I love the addon, if it´s working properly. Maybe it would be usefull, that the addon is always on, as long as you don´t deactivate it manually.

(same with every Anki version from 2.1.26 till 32)

**Comment by oakkitten** [comment]
it appears that the (a bit hacky) mechanism that the script used to store preferences was disabled on some of the recent Anki versions. i [updated](https://github.com/oakkitten/anki-delay-siblings/commit/26613f4a2a6e6d3474c09d69de132254119631a3) the script to use the proper api. uploaded to anki web as well.

please check if this solves the issue

**Comment by itsdomme** [comment]
Yeah! Nice one! Thanks for the fast response.
