### ISSUE TITLE
Cannot enable this add-on

### ISSUE THREAD

**Issue by CouriousSea** [oakkitten/anki-delay-siblings#4]
![error](https://user-images.githubusercontent.com/78986370/107828043-483eff00-6d88-11eb-9ff1-fcd2521e5c2c.png)

I cannot enable this add-on.
Once enabled, will it work on mobile reviews?

**Comment by CouriousSea** [comment]
![image](https://user-images.githubusercontent.com/78986370/107828116-76244380-6d88-11eb-9064-2cccd3d4b4cf.png)

**Comment by CouriousSea** [comment]
![image](https://user-images.githubusercontent.com/78986370/107828159-8dfbc780-6d88-11eb-8068-14557d0c0bf6.png)

**Comment by CouriousSea** [comment]
ok! I just found my answer here :)
https://github.com/oakkitten/anki-delay-siblings/issues/1

**Comment by oakkitten** [comment]
yeah you need to select the deck first.

> Once enabled, will it work on mobile reviews?

do you mean Anki-Android or AnkiMobile? as fair as i know, add-ons only work on the desktop version of Anki
