### ISSUE TITLE
Is it possible to toggle "Enable sibling delaying" for all deck once?

### ISSUE THREAD

**Issue by msnjuegos** [oakkitten/anki-delay-siblings#5]
If you have several decks it is a bit tedious to verify if the addon is activated deck by deck. A global option to toggle for all deck at once would be useful.
Or at least have an option to enable this addon by default. It could be easy to forgot to activate this option for new decks.

**Comment by oakkitten** [comment]
current behavior is hopefully very simple. having either of the suggested options would be confusing imo. 

how should a global toggle look? if  you put it in the menu alongside the existing toggle, it would be bad as they'd be conflicting with each other. it should be an action, so something like "Toggle enabled for all decks"? but what about decks not known to the plugin? and what would the other option do? suppose you have deck A that's disabled (default) and deck B that's enabled. what would changing the default would do?  toggle enabled for deck A? keep current status quo? as for new decks, we'd have to somehow hook into deck creation or something? currently, the plugin only knows about decks it has seen...

i just don't see a simple and straightforward way of doing something like this. and-- i'm not sure how is this a problem in the first place? you will eventually notice if you forget to enable the plugin through the lack of notifications. and people don't normally have too many decks do they, and don't create new decks too often?

**Comment by msnjuegos** [comment]
Well, you are right in your thoughts. When I installed the add-on, it was a bit tedious to enable the option deck by deck (I have a main deck with ~20 subdecks), so I thought that if it could be enabled only once, for example toggling only in the parent deck, would be enough to activate it in all subdecks. 

I didn't think at that moment about the problems that you said. Anyway, the time spent manually enabling deck by deck is nothing compared to the efficiency of this add-on, which has been very useful for me.
Thanks!
